#指定运行环境
language: node_js
#指定nodejs版本，可以指定多个
node_js:
  - '12'

#运行的脚本命令
script:
  - npm run lint:travis
  - npm run test:unit

before_deploy:
  - npm run build

deploy:
  provider: releases
  github_token: GITHUB_OAUTH_TOKEN
  file: dist/**/*
  cleanup: false
  on:
    tags: true
