#指定运行环境
language: node_js
#指定nodejs版本，可以指定多个
node_js:
  - '12'

#运行的脚本命令
script:
  - npm run lint:travis
  - npm run test:unit


#指定分支，只有指定的分支提交时才会运行脚本
branches:
  only:
    - master
    - develop

before_deploy:
  - npm run build

deploy:
  provider: github
  github_token: $GITHUB_TOKEN
  file: dist/**/*
  skip_cleanup: true
  on:
    tags: true
