#指定运行环境
language: node_js
#指定nodejs版本，可以指定多个
node_js:
  - '12'

cache:
  yarn: true
  directories:
    - node_modules
    - ~/.npm
    - ~/.cache

env:
  - TEST_SUITE="./ci-script/travis-job-codecov.sh"
  - TEST_SUITE="./ci-script/travis-job-cypress.sh"
  - TEST_SUITE="./ci-script/travis-job-linter.sh"
#运行的脚本命令
script: ./${TEST_SUITE}


#指定分支，只有指定的分支提交时才会运行脚本
branches:
  only:
    - master
    - develop
